#!/bin/sh

FILE=$1
MSG=$(cat $FILE)
VERSION=`cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[", ]//g'`

if [ -z "$VERSION" ]
then 
    exit 0;
fi

if echo $MSG | grep -q -e "\[skip version\]" -e "\[no version\]"; then
  echo "Skipping version bump";
  exit 0;
fi

if [ -n "$VERSION" ]
then
    sed -i.bak -e "1s/^/$VERSION /" $FILE
fi

exit 0;