import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <div>
      <nav className="bg-blue-500 text-white p-4">
        <h1 className="text-2xl">Navbar</h1>
      </nav>
      <main className="container mx-auto mt-4 p-4 bg-white rounded-lg shadow-md mb-4">
        {children}
      </main>
    </div>
    </html>
  )
}

