import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <div className="bg-primary">
        <main className="flex justify-center items-center h-screen  p-4 md:p-24">
          {children}
        </main>
      </div>
    </html>
  );
}
