import Navbar from "./commons/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Fast&Punctuals",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <div className="bg-primary">
        <Navbar />
        <main
          className={`${poppins.className} container mx-auto flex items-center h-screen justify-center p-4 md:p-24`}
        >
          {children}
        </main>
      </div>
    </html>
  );
}
