import Navbar from "./commons/Navbar";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <div className="bg-primary">
        <Navbar />
        <main className="flex items-center h-screen justify-between p-4 md:p-24">
          {children}
        </main>
      </div>
    </html>
  );
}
